RiverRat/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;

namespace RiverRat.Controllers
{
    public class ArtistController : Controller
    {
        //
        // GET: /Artist/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Gallery(string id) //string artistName)
        {
            List<Models.Photo> photos = new List<Models.Photo>();
            string artistName = id;
            ViewBag.ArtistName = artistName;

            var files= from f in System.IO.Directory.GetFiles(Server.MapPath(Url.Content("~/Content/Artists/" + artistName)))
                           where System.IO.Path.GetFileName(f).ToUpper().StartsWith("TAT")
                           select f;
            foreach (string fileName in files)
            {
                photos.Add(new Models.Photo { FileName = artistName + "/" + System.IO.Path.GetFileName(fileName), Title = GetTitle(fileName), SortKey = GetSortKey(fileName)  });
            }

            photos.Sort((p1, p2) => { return p1.SortKey.CompareTo(p2.SortKey); });

            Models.Artist artist = new Models.Artist { Name = artistName, Photos = photos };

            return View(artist);
        }

        /// <summary>
        /// Parses file name for the sort key
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns>If no sort key is found then we return the max value for an integer</returns>
        private decimal GetSortKey(string fileName)
        {
            string[] words = System.IO.Path.GetFileNameWithoutExtension(fileName).Split('_');
            decimal sortKey = decimal.MaxValue;

            if (words.Length > 1)
            {
                decimal.TryParse(words[1], out sortKey);
            }
            return sortKey;
        }

        /// <summary>
        /// Parses the file name and returns a formatted title from the filename
        /// </summary>
        /// <param name="fileName">Example: TAT_2030_This_is_Andrews_favorite</param>
        /// <returns>Formatted title</returns>
        private string GetTitle(string fileName)
        {
            StringBuilder title = new StringBuilder();
            string[] words = System.IO.Path.GetFileNameWithoutExtension(fileName).Split('_');
            int index = 1;

            foreach (string word in words)
            {
                if (index > 2)
                {
                    //Puts spaces in the title that replaces the underscores
                    if (index > 3)
                    {
                        title.Append(" ");
                    }
                    title.Append(word);
                }
                index++;
            }
            return title.ToString();
        }

    }
}

RiverRat/Controllers/PiercingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RiverRat.Controllers
{
    public class PiercingController : Controller
    {
        //
        // GET: /Piercing/

        public void Index() 
        {
            Response.Redirect("~/Artist/Gallery/Piercings/");
        }

    }
}

RiverRat/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace RiverRat.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

RiverRat/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="@Url.Content("~/Content/jquery.mobile-1.0b3.min.css")" />
        <link rel="stylesheet" href="@Url.Content("~/Content/Site.Mobile.css")" />
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")"></script>
        <script type="text/javascript">
            $(document).bind("mobileinit", function() {
                // As of Beta 2, jQuery Mobile's Ajax navigation does not work in all cases (e.g.,
                // when navigating from a mobile to a non-mobile page), hence disabling it.
                $.mobile.ajaxEnabled = false;
            });
        </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.mobile-1.0b3.min.js")"></script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <header>
                <img alt="River Rat Tattoo Logo" src="@Url.Content("~/Images/new_braunfels_river_rat_tattoo_logo.png")" class="thumbnail-border" width="100" />
            </header>
        </div>
        <div class="content-wrapper">
            <ul data-role="listview" data-inset="true">
                <li class=item>@Html.ActionLink("Location", "Location", "Home")</li>
                <li class=item>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li class=item>@Html.ActionLink("Artists", "Index", "Artist")</li>
                <li class=item>@Html.ActionLink("Piercings", "Index", "Piercing")</li>
            </ul>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

RiverRat/Views/Shared/_Layout.android.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="@Url.Content("~/Content/jquery.mobile-1.0b3.min.css")" />
        <link rel="stylesheet" href="@Url.Content("~/Content/Site.Mobile.css")" />
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")"></script>
        <script type="text/javascript">
            $(document).bind("mobileinit", function() {
                // As of Beta 2, jQuery Mobile's Ajax navigation does not work in all cases (e.g.,
                // when navigating from a mobile to a non-mobile page), hence disabling it.
                $.mobile.ajaxEnabled = false;
            });
        </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.mobile-1.0b3.min.js")"></script>
    </head> 
<body> 

    <div data-role="page" data-theme="e">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <header>
                <img alt="River Rat Tattoo Logo" src="@Url.Content("~/Images/new_braunfels_river_rat_tattoo_logo.png")" class="thumbnail-border" width="100" />
            </header>
        </div>
        <div class="content-wrapper">
            <ul data-role="listview" data-inset="true">
                <li class=item>@Html.ActionLink("Tracy", "Gallery/Tracy", "Artist")</li>
                <li class=item>@Html.ActionLink("Jess", "Gallery/Jess", "Artist")</li>
                <li class=item>@Html.ActionLink("Andrew", "Gallery/Andrew", "Artist")</li>
                <li class=item>@Html.ActionLink("Location", "Location", "Home")</li>
                <li class=item>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

RiverRat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="Description" content="New Braunfels Premier Tattoo Shop Piercings" />
        <title>@ViewBag.Title - New Braunfels River Rat Tattoos and Piercings</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/themes/base/css", "~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("Styles", false)
    </head>
    <body>
        <header>
            @Html.Partial("_ViewSwitcher")
            <table align="center">
                <tr>
                    <td>
                        <img alt="River Rat Tattoo Logo" src="@Url.Content("~/Images/new_braunfels_river_rat_tattoo_logo.png")" class="thumbnail-border" width="400" />
                    </td>
                    <td>
                        <img alt="River Rat Tattoo Sign" src="@Url.Content("~/Images/new_braunfels_river_rat_tattoo_shop_sign.jpg")" class="thumbnail-border" width="400" />
                    </td>
                </tr>
            </table>
            <div class="content-wrapper">
                <div class="float-right">
                    <p class="site-title">@Html.ActionLink("Get inked!", "Index", "Home")</p>
                </div>
                <div class="float-left">
                    <nav>
                        <ul id="navlist">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li id="active"><a href="#">Artists</a>
                                <ul id="subnavlist">
                                    <li>@Html.ActionLink("Tracy", "Gallery/Tracy", "Artist")</li>
                                    <li>@Html.ActionLink("Jess", "Gallery/Jess", "Artist")</li>
                                    <li>@Html.ActionLink("Andrew", "Gallery/Andrew", "Artist")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Piercings", "Index", "Piercing")</li>
                            <li>@Html.ActionLink("Location", "Location", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - River Rat Tattoos!</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://www.facebook.com/RiverRatTattoos" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com/riverrattattoos" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>


    </body>
</html>

RiverRat/Views/Shared/_Layout.iphone.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="@Url.Content("~/Content/jquery.mobile-1.0b3.min.css")" />
        <link rel="stylesheet" href="@Url.Content("~/Content/Site.Mobile.css")" />
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")"></script>
        <script type="text/javascript">
            $(document).bind("mobileinit", function() {
                // As of Beta 2, jQuery Mobile's Ajax navigation does not work in all cases (e.g.,
                // when navigating from a mobile to a non-mobile page), hence disabling it.
                $.mobile.ajaxEnabled = false;
            });
        </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.mobile-1.0b3.min.js")"></script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <header>
                <img alt="River Rat Tattoo Logo" src="@Url.Content("~/Images/rrt-logo.png")" class="thumbnail-border" width="100" />
            </header>
        </div>
        <div class="content-wrapper">
            <ul data-role="listview" data-inset="true">
                <li class=item>@Html.ActionLink("Tracy", "Gallery/Tracy", "Artist")</li>
                <li class=item>@Html.ActionLink("Jess", "Gallery/Jess", "Artist")</li>
                <li class=item>@Html.ActionLink("Andrew", "Gallery/Andrew", "Artist")</li>
                <li class=item>@Html.ActionLink("Location", "Location", "Home")</li>
                <li class=item>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

RiverRat/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}